global using Interfaces;
global using Microsoft.Extensions.Logging;
global using Microsoft.Maui;
global using Microsoft.Maui.Accessibility;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Controls.Hosting;
global using Microsoft.Maui.Hosting;
global using System;
global using System.Threading.Tasks;
global using ServiceRegistry;
global using System.Threading;
global using RedStar.Amounts;
global using RedStar.Amounts.StandardUnits;
global using MetWorksModels.Weather;
global using MetWorksWeather.DeviceSelection;
global using System.Diagnostics;
global using ILogger = Interfaces.ILogger;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using SystemTimer = System.Timers.Timer;
global using ThreadingTimer = System.Threading.Timer;
global using System.Timers;
global using Microsoft.Maui.ApplicationModel;
