<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetWorks_Common_Settings\MetWorks_Common_Settings.csproj" />
    <ProjectReference Include="..\MetWorks_Constants\MetWorks_Constants.csproj" />
    <ProjectReference Include="..\MetWorks_Data_Sqlite\MetWorks_Data_Sqlite.csproj" />
    <ProjectReference Include="..\MetWorks_Interfaces\MetWorks_Interfaces.csproj" />
    <ProjectReference Include="..\MetWorks_Ingest\MetWorks_Ingest.csproj" />
    <ProjectReference Include="..\MetWorks_Resource_Store\MetWorks_Resource_Store.csproj" />
  </ItemGroup>

</Project>
