global using Interfaces;
global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using Utility;
global using System.Linq;
global using YamlDotNet.Serialization;
global using YamlDotNet.Serialization.NamingConventions;
global using StaticDataStore;